<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2016-10-11T01:00:30+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      api_keys.google.maps
 * @group     app
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'api_keys' => array(
        'google' => array(
            'maps' => 'AIzaSyC72UPYEPjI9KtnYs8hzN_8EuG9QnbVt60',
        ),
    ),
);
