<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2016-10-10T18:53:10+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.do_page_reindex_check
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'site' => 'Wyoming Landscape Contractors',
    'version_installed' => '5.7.5.9',
    'misc' => array(
        'access_entity_updated' => 1473520622,
        'latest_version' => '5.7.5.9',
        'do_page_reindex_check' => false,
    ),
    'cache' => array(
        'blocks' => false,
        'assets' => false,
        'theme_css' => false,
        'overrides' => false,
        'pages' => '0',
        'full_page_lifetime' => 'custom',
        'full_page_lifetime_value' => '1',
    ),
    'theme' => array(
        'compress_preprocessor_output' => false,
        'generate_less_sourcemap' => false,
    ),
);
