<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2016-09-10T15:17:02+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.access_entity_updated
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'site' => 'Wyoming Landscape Contractors',
    'version_installed' => '5.7.5.9',
    'misc' => array(
        'access_entity_updated' => 1473520622,
    ),
);
